FROM node:18

RUN mkdir -p /usr/src/app/
WORKDIR /usr/src/app/

COPY . .
RUN npm i

WORKDIR /usr/src/app/packages/locales

RUN npm run compile

WORKDIR /usr/src/app/apps/api

EXPOSE 3000

CMD npm run start